/* Auto-generated by generate_can_signals.py — do not edit manually. */
/* Re-run after any DBC change and commit the output.                */

#include "can_signals.h"

/* ── WSBFL_BrakePressure ── */
struct WSBFL_BrakePressure {
    int64_t  RearBrakePressure : 16;
    uint64_t FILLER_END : 48;
};

/**
 * @brief  Encode WSBFL_BrakePressure
 *         ID: 0x04120208  (68289032)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  RearBrakePressure                        [scale=1, offset=0, signed, 16bit]
 */
void encode_WSBFL_BrakePressure(uint8_t data[8], int64_t RearBrakePressure)
{
    struct WSBFL_BrakePressure frame = {0};

    frame.RearBrakePressure = (int64_t)(RearBrakePressure);
    memcpy(data, &frame, 8);
}

int sendCAN_WSBFL_BrakePressure(int64_t RearBrakePressure)
{
    uint8_t data[8];
    encode_WSBFL_BrakePressure(data, RearBrakePressure);
    return HIL_CAN_Transmit(&hcan3, 0x04120208UL, 8, data);
}

/* ── WSBRR_Speed ── */
struct WSBRR_Speed {
    int64_t  RRSpeedKPH : 16;
    uint64_t RRSpeedRPM : 16;
    uint64_t FILLER_END : 32;
};

/**
 * @brief  Encode WSBRR_Speed
 *         ID: 0x0400020B  (67109387)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  RRSpeedKPH                               [scale=0.04, offset=0, signed, 16bit]
 * @param  RRSpeedRPM                               [scale=1, offset=0, unsigned, 16bit]
 */
void encode_WSBRR_Speed(uint8_t data[8], float RRSpeedKPH, uint64_t RRSpeedRPM)
{
    struct WSBRR_Speed frame = {0};

    frame.RRSpeedKPH = (int64_t)((RRSpeedKPH) / (0.04f));
    frame.RRSpeedRPM = (uint64_t)(RRSpeedRPM);
    memcpy(data, &frame, 8);
}

int sendCAN_WSBRR_Speed(float RRSpeedKPH, uint64_t RRSpeedRPM)
{
    uint8_t data[8];
    encode_WSBRR_Speed(data, RRSpeedKPH, RRSpeedRPM);
    return HIL_CAN_Transmit(&hcan3, 0x0400020BUL, 8, data);
}

/* ── WSBRL_Speed ── */
struct WSBRL_Speed {
    int64_t  RLSpeedKPH : 16;
    int64_t  RLSpeedRPM : 32;
};

/**
 * @brief  Encode WSBRL_Speed
 *         ID: 0x0400020A  (67109386)  Length: 6B
 * @param  data  Output buffer, must be >= 6 bytes
 * @param  RLSpeedKPH                               [scale=0.04, offset=0, signed, 16bit]
 * @param  RLSpeedRPM                               [scale=1, offset=0, signed, 32bit]
 */
void encode_WSBRL_Speed(uint8_t data[6], float RLSpeedKPH, int64_t RLSpeedRPM)
{
    struct WSBRL_Speed frame = {0};

    frame.RLSpeedKPH = (int64_t)((RLSpeedKPH) / (0.04f));
    frame.RLSpeedRPM = (int64_t)(RLSpeedRPM);
    memcpy(data, &frame, 6);
}

int sendCAN_WSBRL_Speed(float RLSpeedKPH, int64_t RLSpeedRPM)
{
    uint8_t data[6];
    encode_WSBRL_Speed(data, RLSpeedKPH, RLSpeedRPM);
    return HIL_CAN_Transmit(&hcan3, 0x0400020AUL, 6, data);
}

/* ── PDU_Car_State ── */
struct PDU_Car_State {
    int64_t  CarStateIsLV : 1;
    int64_t  CarStateIsEM : 1;
    uint64_t FILLER_2 : 6;
    int64_t  CarStateIsHV : 1;
    uint64_t FILLER_END : 55;
};

/**
 * @brief  Encode PDU_Car_State
 *         ID: 0x0BAAFF03  (195755779)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  CarStateIsLV                             [scale=1, offset=0, signed, 1bit]
 * @param  CarStateIsEM                             [scale=1, offset=0, signed, 1bit]
 * @param  CarStateIsHV                             [scale=1, offset=0, signed, 1bit]
 */
void encode_PDU_Car_State(uint8_t data[8], int64_t CarStateIsLV, int64_t CarStateIsEM, int64_t CarStateIsHV)
{
    struct PDU_Car_State frame = {0};

    frame.CarStateIsLV = (int64_t)(CarStateIsLV);
    frame.CarStateIsEM = (int64_t)(CarStateIsEM);
    frame.CarStateIsHV = (int64_t)(CarStateIsHV);
    memcpy(data, &frame, 8);
}

int sendCAN_PDU_Car_State(int64_t CarStateIsLV, int64_t CarStateIsEM, int64_t CarStateIsHV)
{
    uint8_t data[8];
    encode_PDU_Car_State(data, CarStateIsLV, CarStateIsEM, CarStateIsHV);
    return HIL_CAN_Transmit(&hcan3, 0x0BAAFF03UL, 8, data);
}

/* ── TractionControlConfig ── */
struct TractionControlConfig {
    uint64_t TC_kP : 16;
    uint64_t TC_kI : 16;
    uint64_t TC_kD : 16;
    int64_t  TC_desiredSlipPercent : 16;
};

/**
 * @brief  Encode TractionControlConfig
 *         ID: 0x080302C0  (134415040)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  TC_kP                                    [scale=0.01, offset=0, unsigned, 16bit]
 * @param  TC_kI                                    [scale=0.01, offset=0, unsigned, 16bit]
 * @param  TC_kD                                    [scale=0.01, offset=0, unsigned, 16bit]
 * @param  TC_desiredSlipPercent                    [scale=0.0001, offset=0, signed, 16bit]
 */
void encode_TractionControlConfig(uint8_t data[8], float TC_kP, float TC_kI, float TC_kD, float TC_desiredSlipPercent)
{
    struct TractionControlConfig frame = {0};

    frame.TC_kP = (uint64_t)((TC_kP) / (0.01f));
    frame.TC_kI = (uint64_t)((TC_kI) / (0.01f));
    frame.TC_kD = (uint64_t)((TC_kD) / (0.01f));
    frame.TC_desiredSlipPercent = (int64_t)((TC_desiredSlipPercent) / (0.0001f));
    memcpy(data, &frame, 8);
}

int sendCAN_TractionControlConfig(float TC_kP, float TC_kI, float TC_kD, float TC_desiredSlipPercent)
{
    uint8_t data[8];
    encode_TractionControlConfig(data, TC_kP, TC_kI, TC_kD, TC_desiredSlipPercent);
    return HIL_CAN_Transmit(&hcan3, 0x080302C0UL, 8, data);
}

/* ── UartOverCanTx ── */
struct UartOverCanTx {
    int64_t  UartOverCanTX : 8;
};

/**
 * @brief  Encode UartOverCanTx
 *         ID: 0x0406FF02  (67567362)  Length: 1B
 * @param  data  Output buffer, must be >= 1 bytes
 * @param  UartOverCanTX                            [scale=1, offset=0, signed, 8bit]
 */
void encode_UartOverCanTx(uint8_t data[1], int64_t UartOverCanTX)
{
    struct UartOverCanTx frame = {0};

    frame.UartOverCanTX = (int64_t)(UartOverCanTX);
    memcpy(data, &frame, 1);
}

int sendCAN_UartOverCanTx(int64_t UartOverCanTX)
{
    uint8_t data[1];
    encode_UartOverCanTx(data, UartOverCanTX);
    return HIL_CAN_Transmit(&hcan3, 0x0406FF02UL, 1, data);
}

/* ── UartOverCanConfig ── */
struct UartOverCanConfig {
    int64_t  UartOverCanConfigSignal : 8;
};

/**
 * @brief  Encode UartOverCanConfig
 *         ID: 0x0405FF02  (67501826)  Length: 1B
 * @param  data  Output buffer, must be >= 1 bytes
 * @param  UartOverCanConfigSignal                  [scale=1, offset=0, signed, 8bit]
 */
void encode_UartOverCanConfig(uint8_t data[1], int64_t UartOverCanConfigSignal)
{
    struct UartOverCanConfig frame = {0};

    frame.UartOverCanConfigSignal = (int64_t)(UartOverCanConfigSignal);
    memcpy(data, &frame, 1);
}

int sendCAN_UartOverCanConfig(int64_t UartOverCanConfigSignal)
{
    uint8_t data[1];
    encode_UartOverCanConfig(data, UartOverCanConfigSignal);
    return HIL_CAN_Transmit(&hcan3, 0x0405FF02UL, 1, data);
}

/* ── WSBFR_Sensors ── */
struct WSBFR_Sensors {
    uint64_t FR_WheelDistance : 32;
    int64_t  FR_Speed_RAD_S : 16;
    uint64_t FILLER_END : 16;
};

/**
 * @brief  Encode WSBFR_Sensors
 *         ID: 0x04100209  (68157961)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  FR_WheelDistance                         [scale=1, offset=0, unsigned, 32bit]
 * @param  FR_Speed_RAD_S                           [scale=0.0625, offset=0, signed, 16bit]
 */
void encode_WSBFR_Sensors(uint8_t data[8], uint64_t FR_WheelDistance, float FR_Speed_RAD_S)
{
    struct WSBFR_Sensors frame = {0};

    frame.FR_WheelDistance = (uint64_t)(FR_WheelDistance);
    frame.FR_Speed_RAD_S = (int64_t)((FR_Speed_RAD_S) / (0.0625f));
    memcpy(data, &frame, 8);
}

int sendCAN_WSBFR_Sensors(uint64_t FR_WheelDistance, float FR_Speed_RAD_S)
{
    uint8_t data[8];
    encode_WSBFR_Sensors(data, FR_WheelDistance, FR_Speed_RAD_S);
    return HIL_CAN_Transmit(&hcan3, 0x04100209UL, 8, data);
}

/* ── WSBFL_Sensors ── */
struct WSBFL_Sensors {
    uint64_t FL_WheelDistance : 32;
    int64_t  FL_Speed_RAD_S : 16;
    uint64_t FILLER_END : 16;
};

/**
 * @brief  Encode WSBFL_Sensors
 *         ID: 0x04100208  (68157960)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  FL_WheelDistance                         [scale=1, offset=0, unsigned, 32bit]
 * @param  FL_Speed_RAD_S                           [scale=0.0625, offset=0, signed, 16bit]
 */
void encode_WSBFL_Sensors(uint8_t data[8], uint64_t FL_WheelDistance, float FL_Speed_RAD_S)
{
    struct WSBFL_Sensors frame = {0};

    frame.FL_WheelDistance = (uint64_t)(FL_WheelDistance);
    frame.FL_Speed_RAD_S = (int64_t)((FL_Speed_RAD_S) / (0.0625f));
    memcpy(data, &frame, 8);
}

int sendCAN_WSBFL_Sensors(uint64_t FL_WheelDistance, float FL_Speed_RAD_S)
{
    uint8_t data[8];
    encode_WSBFL_Sensors(data, FL_WheelDistance, FL_Speed_RAD_S);
    return HIL_CAN_Transmit(&hcan3, 0x04100208UL, 8, data);
}

/* ── PrechargeState ── */
struct PrechargeState {
    uint64_t PrechargeState : 8;
    uint64_t FILLER_END : 56;
};

/**
 * @brief  Encode PrechargeState
 *         ID: 0x08D4FF01  (148176641)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  PrechargeState                           [scale=1, offset=0, unsigned, 8bit]
 */
void encode_PrechargeState(uint8_t data[8], uint64_t PrechargeState)
{
    struct PrechargeState frame = {0};

    frame.PrechargeState = (uint64_t)(PrechargeState);
    memcpy(data, &frame, 8);
}

int sendCAN_PrechargeState(uint64_t PrechargeState)
{
    uint8_t data[8];
    encode_PrechargeState(data, PrechargeState);
    return HIL_CAN_Transmit(&hcan3, 0x08D4FF01UL, 8, data);
}

/* ── DCU_Heartbeat ── */
struct DCU_Heartbeat {
    int64_t  DCU_Heartbeat_dummydata : 1;
    uint64_t FILLER_END : 7;
};

/**
 * @brief  Encode DCU_Heartbeat
 *         ID: 0x0404FF07  (67436295)  Length: 1B
 * @param  data  Output buffer, must be >= 1 bytes
 * @param  DCU_Heartbeat_dummydata                  [scale=1, offset=0, signed, 1bit]
 */
void encode_DCU_Heartbeat(uint8_t data[1], int64_t DCU_Heartbeat_dummydata)
{
    struct DCU_Heartbeat frame = {0};

    frame.DCU_Heartbeat_dummydata = (int64_t)(DCU_Heartbeat_dummydata);
    memcpy(data, &frame, 1);
}

int sendCAN_DCU_Heartbeat(int64_t DCU_Heartbeat_dummydata)
{
    uint8_t data[1];
    encode_DCU_Heartbeat(data, DCU_Heartbeat_dummydata);
    return HIL_CAN_Transmit(&hcan3, 0x0404FF07UL, 1, data);
}

/* ── PDU_Heartbeat ── */
struct PDU_Heartbeat {
    int64_t  PDU_Heartbeat_dummydata : 1;
    uint64_t FILLER_END : 7;
};

/**
 * @brief  Encode PDU_Heartbeat
 *         ID: 0x0404FF03  (67436291)  Length: 1B
 * @param  data  Output buffer, must be >= 1 bytes
 * @param  PDU_Heartbeat_dummydata                  [scale=1, offset=0, signed, 1bit]
 */
void encode_PDU_Heartbeat(uint8_t data[1], int64_t PDU_Heartbeat_dummydata)
{
    struct PDU_Heartbeat frame = {0};

    frame.PDU_Heartbeat_dummydata = (int64_t)(PDU_Heartbeat_dummydata);
    memcpy(data, &frame, 1);
}

int sendCAN_PDU_Heartbeat(int64_t PDU_Heartbeat_dummydata)
{
    uint8_t data[1];
    encode_PDU_Heartbeat(data, PDU_Heartbeat_dummydata);
    return HIL_CAN_Transmit(&hcan3, 0x0404FF03UL, 1, data);
}

/* ── BMU_Heartbeat ── */
struct BMU_Heartbeat {
    int64_t  BMU_Heartbeat_dummydata : 1;
    uint64_t FILLER_END : 7;
};

/**
 * @brief  Encode BMU_Heartbeat
 *         ID: 0x0404FF01  (67436289)  Length: 1B
 * @param  data  Output buffer, must be >= 1 bytes
 * @param  BMU_Heartbeat_dummydata                  [scale=1, offset=0, signed, 1bit]
 */
void encode_BMU_Heartbeat(uint8_t data[1], int64_t BMU_Heartbeat_dummydata)
{
    struct BMU_Heartbeat frame = {0};

    frame.BMU_Heartbeat_dummydata = (int64_t)(BMU_Heartbeat_dummydata);
    memcpy(data, &frame, 1);
}

int sendCAN_BMU_Heartbeat(int64_t BMU_Heartbeat_dummydata)
{
    uint8_t data[1];
    encode_BMU_Heartbeat(data, BMU_Heartbeat_dummydata);
    return HIL_CAN_Transmit(&hcan3, 0x0404FF01UL, 1, data);
}

/* ── BMU_HV_Power_State ── */
struct BMU_HV_Power_State {
    uint64_t HV_Power_State : 1;
    uint64_t FILLER_END : 7;
};

/**
 * @brief  Encode BMU_HV_Power_State
 *         ID: 0x0425FF01  (69598977)  Length: 1B
 * @param  data  Output buffer, must be >= 1 bytes
 * @param  HV_Power_State                           [scale=1, offset=0, unsigned, 1bit]
 */
void encode_BMU_HV_Power_State(uint8_t data[1], uint64_t HV_Power_State)
{
    struct BMU_HV_Power_State frame = {0};

    frame.HV_Power_State = (uint64_t)(HV_Power_State);
    memcpy(data, &frame, 1);
}

int sendCAN_BMU_HV_Power_State(uint64_t HV_Power_State)
{
    uint8_t data[1];
    encode_BMU_HV_Power_State(data, HV_Power_State);
    return HIL_CAN_Transmit(&hcan3, 0x0425FF01UL, 1, data);
}

/* ── PDU_DTC ── */
struct PDU_DTC {
    uint64_t DTC_CODE : 8;
    int64_t  DTC_Severity : 8;
    int64_t  DTC_Data : 32;
};

/**
 * @brief  Encode PDU_DTC
 *         ID: 0x0000FF03  (65283)  Length: 6B
 * @param  data  Output buffer, must be >= 6 bytes
 * @param  DTC_CODE                                 [scale=1, offset=0, unsigned, 8bit]
 * @param  DTC_Severity                             [scale=1, offset=0, signed, 8bit]
 * @param  DTC_Data                                 [scale=1, offset=0, signed, 32bit]
 */
void encode_PDU_DTC(uint8_t data[6], uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data)
{
    struct PDU_DTC frame = {0};

    frame.DTC_CODE = (uint64_t)(DTC_CODE);
    frame.DTC_Severity = (int64_t)(DTC_Severity);
    frame.DTC_Data = (int64_t)(DTC_Data);
    memcpy(data, &frame, 6);
}

int sendCAN_PDU_DTC(uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data)
{
    uint8_t data[6];
    encode_PDU_DTC(data, DTC_CODE, DTC_Severity, DTC_Data);
    return HIL_CAN_Transmit(&hcan3, 0x0000FF03UL, 6, data);
}

/* ── DCU_DTC ── */
struct DCU_DTC {
    uint64_t DTC_CODE : 8;
    int64_t  DTC_Severity : 8;
    int64_t  DTC_Data : 32;
};

/**
 * @brief  Encode DCU_DTC
 *         ID: 0x0000FF07  (65287)  Length: 6B
 * @param  data  Output buffer, must be >= 6 bytes
 * @param  DTC_CODE                                 [scale=1, offset=0, unsigned, 8bit]
 * @param  DTC_Severity                             [scale=1, offset=0, signed, 8bit]
 * @param  DTC_Data                                 [scale=1, offset=0, signed, 32bit]
 */
void encode_DCU_DTC(uint8_t data[6], uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data)
{
    struct DCU_DTC frame = {0};

    frame.DTC_CODE = (uint64_t)(DTC_CODE);
    frame.DTC_Severity = (int64_t)(DTC_Severity);
    frame.DTC_Data = (int64_t)(DTC_Data);
    memcpy(data, &frame, 6);
}

int sendCAN_DCU_DTC(uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data)
{
    uint8_t data[6];
    encode_DCU_DTC(data, DTC_CODE, DTC_Severity, DTC_Data);
    return HIL_CAN_Transmit(&hcan3, 0x0000FF07UL, 6, data);
}

/* ── BMU_DTC ── */
struct BMU_DTC {
    uint64_t DTC_CODE : 8;
    int64_t  DTC_Severity : 8;
    int64_t  DTC_Data : 32;
};

/**
 * @brief  Encode BMU_DTC
 *         ID: 0x0000FF01  (65281)  Length: 6B
 * @param  data  Output buffer, must be >= 6 bytes
 * @param  DTC_CODE                                 [scale=1, offset=0, unsigned, 8bit]
 * @param  DTC_Severity                             [scale=1, offset=0, signed, 8bit]
 * @param  DTC_Data                                 [scale=1, offset=0, signed, 32bit]
 */
void encode_BMU_DTC(uint8_t data[6], uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data)
{
    struct BMU_DTC frame = {0};

    frame.DTC_CODE = (uint64_t)(DTC_CODE);
    frame.DTC_Severity = (int64_t)(DTC_Severity);
    frame.DTC_Data = (int64_t)(DTC_Data);
    memcpy(data, &frame, 6);
}

int sendCAN_BMU_DTC(uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data)
{
    uint8_t data[6];
    encode_BMU_DTC(data, DTC_CODE, DTC_Severity, DTC_Data);
    return HIL_CAN_Transmit(&hcan3, 0x0000FF01UL, 6, data);
}

/* ── ChargeCart_DTC ── */
struct ChargeCart_DTC {
    uint64_t DTC_CODE : 8;
    int64_t  DTC_Severity : 8;
    int64_t  DTC_Data : 32;
};

/**
 * @brief  Encode ChargeCart_DTC
 *         ID: 0x0000FF04  (65284)  Length: 6B
 * @param  data  Output buffer, must be >= 6 bytes
 * @param  DTC_CODE                                 [scale=1, offset=0, unsigned, 8bit]
 * @param  DTC_Severity                             [scale=1, offset=0, signed, 8bit]
 * @param  DTC_Data                                 [scale=1, offset=0, signed, 32bit]
 */
void encode_ChargeCart_DTC(uint8_t data[6], uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data)
{
    struct ChargeCart_DTC frame = {0};

    frame.DTC_CODE = (uint64_t)(DTC_CODE);
    frame.DTC_Severity = (int64_t)(DTC_Severity);
    frame.DTC_Data = (int64_t)(DTC_Data);
    memcpy(data, &frame, 6);
}

int sendCAN_ChargeCart_DTC(uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data)
{
    uint8_t data[6];
    encode_ChargeCart_DTC(data, DTC_CODE, DTC_Severity, DTC_Data);
    return HIL_CAN_Transmit(&hcan3, 0x0000FF04UL, 6, data);
}

/* ── TempCoolantRight ── */
struct TempCoolantRight {
    int64_t  TempInletRadMotorRight : 10;
    int64_t  TempOutletRadMotorRight : 10;
    uint64_t FILLER_END : 44;
};

/**
 * @brief  Encode TempCoolantRight
 *         ID: 0x18000213  (402653715)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  TempInletRadMotorRight                   [scale=0.25, offset=90, signed, 10bit]
 * @param  TempOutletRadMotorRight                  [scale=0.25, offset=90, signed, 10bit]
 */
void encode_TempCoolantRight(uint8_t data[8], float TempInletRadMotorRight, float TempOutletRadMotorRight)
{
    struct TempCoolantRight frame = {0};

    frame.TempInletRadMotorRight = (int64_t)(((TempInletRadMotorRight) - (90.0f)) / (0.25f));
    frame.TempOutletRadMotorRight = (int64_t)(((TempOutletRadMotorRight) - (90.0f)) / (0.25f));
    memcpy(data, &frame, 8);
}

int sendCAN_TempCoolantRight(float TempInletRadMotorRight, float TempOutletRadMotorRight)
{
    uint8_t data[8];
    encode_TempCoolantRight(data, TempInletRadMotorRight, TempOutletRadMotorRight);
    return HIL_CAN_Transmit(&hcan3, 0x18000213UL, 8, data);
}

/* ── TempCoolantLeft ── */
struct TempCoolantLeft {
    int64_t  TempInletRadMotorLeft : 10;
    int64_t  TempOutletRadMotorLeft : 10;
    uint64_t FILLER_END : 44;
};

/**
 * @brief  Encode TempCoolantLeft
 *         ID: 0x18000212  (402653714)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  TempInletRadMotorLeft                    [scale=0.25, offset=90, signed, 10bit]
 * @param  TempOutletRadMotorLeft                   [scale=0.25, offset=90, signed, 10bit]
 */
void encode_TempCoolantLeft(uint8_t data[8], float TempInletRadMotorLeft, float TempOutletRadMotorLeft)
{
    struct TempCoolantLeft frame = {0};

    frame.TempInletRadMotorLeft = (int64_t)(((TempInletRadMotorLeft) - (90.0f)) / (0.25f));
    frame.TempOutletRadMotorLeft = (int64_t)(((TempOutletRadMotorLeft) - (90.0f)) / (0.25f));
    memcpy(data, &frame, 8);
}

int sendCAN_TempCoolantLeft(float TempInletRadMotorLeft, float TempOutletRadMotorLeft)
{
    uint8_t data[8];
    encode_TempCoolantLeft(data, TempInletRadMotorLeft, TempOutletRadMotorLeft);
    return HIL_CAN_Transmit(&hcan3, 0x18000212UL, 8, data);
}

/* ── BMU_stateBatteryHV ── */
struct BMU_stateBatteryHV {
    uint64_t VoltageBatteryHV : 20;
    int64_t  CurrentDCBatteryHV : 22;
    int64_t  PowerBatteryHV : 22;
};

/**
 * @brief  Encode BMU_stateBatteryHV
 *         ID: 0x08000201  (134218241)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  VoltageBatteryHV                         [scale=1, offset=0, unsigned, 20bit]
 * @param  CurrentDCBatteryHV                       [scale=0.001, offset=0, signed, 22bit]
 * @param  PowerBatteryHV                           [scale=0.01, offset=0, signed, 22bit]
 */
void encode_BMU_stateBatteryHV(uint8_t data[8], uint64_t VoltageBatteryHV, float CurrentDCBatteryHV, float PowerBatteryHV)
{
    struct BMU_stateBatteryHV frame = {0};

    frame.VoltageBatteryHV = (uint64_t)(VoltageBatteryHV);
    frame.CurrentDCBatteryHV = (int64_t)((CurrentDCBatteryHV) / (0.001f));
    frame.PowerBatteryHV = (int64_t)((PowerBatteryHV) / (0.01f));
    memcpy(data, &frame, 8);
}

int sendCAN_BMU_stateBatteryHV(uint64_t VoltageBatteryHV, float CurrentDCBatteryHV, float PowerBatteryHV)
{
    uint8_t data[8];
    encode_BMU_stateBatteryHV(data, VoltageBatteryHV, CurrentDCBatteryHV, PowerBatteryHV);
    return HIL_CAN_Transmit(&hcan3, 0x08000201UL, 8, data);
}

/* ── PDU_ChannelStatus ── */
struct PDU_ChannelStatus {
    uint64_t FILLER_0 : 40;
    int64_t  StatusPowerInverter : 4;
    int64_t  StatusPowerRadiator : 4;
    uint64_t FILLER_END : 8;
};

/**
 * @brief  Encode PDU_ChannelStatus
 *         ID: 0x04060203  (67502595)  Length: 7B
 * @param  data  Output buffer, must be >= 7 bytes
 * @param  StatusPowerInverter                      [scale=1, offset=0, signed, 4bit]
 * @param  StatusPowerRadiator                      [scale=1, offset=0, signed, 4bit]
 */
void encode_PDU_ChannelStatus(uint8_t data[7], int64_t StatusPowerInverter, int64_t StatusPowerRadiator)
{
    struct PDU_ChannelStatus frame = {0};

    frame.StatusPowerInverter = (int64_t)(StatusPowerInverter);
    frame.StatusPowerRadiator = (int64_t)(StatusPowerRadiator);
    memcpy(data, &frame, 7);
}

int sendCAN_PDU_ChannelStatus(int64_t StatusPowerInverter, int64_t StatusPowerRadiator)
{
    uint8_t data[7];
    encode_PDU_ChannelStatus(data, StatusPowerInverter, StatusPowerRadiator);
    return HIL_CAN_Transmit(&hcan3, 0x04060203UL, 7, data);
}

/* ── BMU_batteryStatusHV ── */
struct BMU_batteryStatusHV {
    uint64_t StateBatteryChargeHV : 10;
    uint64_t StateBatteryHealthHV : 10;
    uint64_t StateBatteryPowerHV : 12;
    uint64_t FILLER_32 : 20;
    int64_t  StateBMS : 4;
    uint64_t FILLER_END : 8;
};

/**
 * @brief  Encode BMU_batteryStatusHV
 *         ID: 0x08041001  (134483969)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  StateBatteryChargeHV                     [scale=0.1, offset=0, unsigned, 10bit]
 * @param  StateBatteryHealthHV                     [scale=0.1, offset=0, unsigned, 10bit]
 * @param  StateBatteryPowerHV                      [scale=0.1, offset=0, unsigned, 12bit]
 * @param  StateBMS                                 [scale=1, offset=0, signed, 4bit]
 */
void encode_BMU_batteryStatusHV(uint8_t data[8], float StateBatteryChargeHV, float StateBatteryHealthHV, float StateBatteryPowerHV, int64_t StateBMS)
{
    struct BMU_batteryStatusHV frame = {0};

    frame.StateBatteryChargeHV = (uint64_t)((StateBatteryChargeHV) / (0.1f));
    frame.StateBatteryHealthHV = (uint64_t)((StateBatteryHealthHV) / (0.1f));
    frame.StateBatteryPowerHV = (uint64_t)((StateBatteryPowerHV) / (0.1f));
    frame.StateBMS = (int64_t)(StateBMS);
    memcpy(data, &frame, 8);
}

int sendCAN_BMU_batteryStatusHV(float StateBatteryChargeHV, float StateBatteryHealthHV, float StateBatteryPowerHV, int64_t StateBMS)
{
    uint8_t data[8];
    encode_BMU_batteryStatusHV(data, StateBatteryChargeHV, StateBatteryHealthHV, StateBatteryPowerHV, StateBMS);
    return HIL_CAN_Transmit(&hcan3, 0x08041001UL, 8, data);
}

/* ── BMU_stateBusHV ── */
struct BMU_stateBusHV {
    uint64_t VoltageBusHV : 16;
    uint64_t FILLER_END : 48;
};

/**
 * @brief  Encode BMU_stateBusHV
 *         ID: 0x08101201  (135270913)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  VoltageBusHV                             [scale=0.01, offset=0, unsigned, 16bit]
 */
void encode_BMU_stateBusHV(uint8_t data[8], float VoltageBusHV)
{
    struct BMU_stateBusHV frame = {0};

    frame.VoltageBusHV = (uint64_t)((VoltageBusHV) / (0.01f));
    memcpy(data, &frame, 8);
}

int sendCAN_BMU_stateBusHV(float VoltageBusHV)
{
    uint8_t data[8];
    encode_BMU_stateBusHV(data, VoltageBusHV);
    return HIL_CAN_Transmit(&hcan3, 0x08101201UL, 8, data);
}

/* ── MC_Modulation_And_Flux_Info ── */
struct MC_Modulation_And_Flux_Info {
    int64_t  INV_Modulation_Index : 16;
    int64_t  INV_Flux_Weakening_Output : 16;
    int64_t  INV_Id_Command : 16;
    int64_t  INV_Iq_Command : 16;
};

/**
 * @brief  Encode MC_Modulation_And_Flux_Info
 *         ID: 0x0CFFAD01  (218082561)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Modulation_Index                     [scale=0.0001, offset=0, signed, 16bit]
 * @param  INV_Flux_Weakening_Output                [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Id_Command                           [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Iq_Command                           [scale=0.1, offset=0, signed, 16bit]
 */
void encode_MC_Modulation_And_Flux_Info(uint8_t data[8], float INV_Modulation_Index, float INV_Flux_Weakening_Output, float INV_Id_Command, float INV_Iq_Command)
{
    struct MC_Modulation_And_Flux_Info frame = {0};

    frame.INV_Modulation_Index = (int64_t)((INV_Modulation_Index) / (0.0001f));
    frame.INV_Flux_Weakening_Output = (int64_t)((INV_Flux_Weakening_Output) / (0.1f));
    frame.INV_Id_Command = (int64_t)((INV_Id_Command) / (0.1f));
    frame.INV_Iq_Command = (int64_t)((INV_Iq_Command) / (0.1f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Modulation_And_Flux_Info(float INV_Modulation_Index, float INV_Flux_Weakening_Output, float INV_Id_Command, float INV_Iq_Command)
{
    uint8_t data[8];
    encode_MC_Modulation_And_Flux_Info(data, INV_Modulation_Index, INV_Flux_Weakening_Output, INV_Id_Command, INV_Iq_Command);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFAD01UL, 8, data);
}

/* ── MC_Torque_And_Timer_Info ── */
struct MC_Torque_And_Timer_Info {
    int64_t  INV_Commanded_Torque : 16;
    int64_t  INV_Torque_Feedback : 16;
    uint64_t INV_Power_On_Timer : 32;
};

/**
 * @brief  Encode MC_Torque_And_Timer_Info
 *         ID: 0x0CFFAC01  (218082305)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Commanded_Torque                     [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Torque_Feedback                      [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Power_On_Timer                       [scale=0.003, offset=0, unsigned, 32bit]
 */
void encode_MC_Torque_And_Timer_Info(uint8_t data[8], float INV_Commanded_Torque, float INV_Torque_Feedback, float INV_Power_On_Timer)
{
    struct MC_Torque_And_Timer_Info frame = {0};

    frame.INV_Commanded_Torque = (int64_t)((INV_Commanded_Torque) / (0.1f));
    frame.INV_Torque_Feedback = (int64_t)((INV_Torque_Feedback) / (0.1f));
    frame.INV_Power_On_Timer = (uint64_t)((INV_Power_On_Timer) / (0.003f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Torque_And_Timer_Info(float INV_Commanded_Torque, float INV_Torque_Feedback, float INV_Power_On_Timer)
{
    uint8_t data[8];
    encode_MC_Torque_And_Timer_Info(data, INV_Commanded_Torque, INV_Torque_Feedback, INV_Power_On_Timer);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFAC01UL, 8, data);
}

/* ── MC_Read_Write_Param_Response ── */
struct MC_Read_Write_Param_Response {
    uint64_t INV_Parameter_Response_Addr : 16;
    uint64_t INV_Parameter_Response_Write_OK : 1;
    uint64_t FILLER_17 : 15;
    int64_t  INV_Parameter_Response_Data : 16;
    uint64_t FILLER_END : 16;
};

/**
 * @brief  Encode MC_Read_Write_Param_Response
 *         ID: 0x0CFFC201  (218087937)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Parameter_Response_Addr              [scale=1, offset=0, unsigned, 16bit]
 * @param  INV_Parameter_Response_Write_OK          [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Parameter_Response_Data              [scale=1, offset=0, signed, 16bit]
 */
void encode_MC_Read_Write_Param_Response(uint8_t data[8], uint64_t INV_Parameter_Response_Addr, uint64_t INV_Parameter_Response_Write_OK, int64_t INV_Parameter_Response_Data)
{
    struct MC_Read_Write_Param_Response frame = {0};

    frame.INV_Parameter_Response_Addr = (uint64_t)(INV_Parameter_Response_Addr);
    frame.INV_Parameter_Response_Write_OK = (uint64_t)(INV_Parameter_Response_Write_OK);
    frame.INV_Parameter_Response_Data = (int64_t)(INV_Parameter_Response_Data);
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Read_Write_Param_Response(uint64_t INV_Parameter_Response_Addr, uint64_t INV_Parameter_Response_Write_OK, int64_t INV_Parameter_Response_Data)
{
    uint8_t data[8];
    encode_MC_Read_Write_Param_Response(data, INV_Parameter_Response_Addr, INV_Parameter_Response_Write_OK, INV_Parameter_Response_Data);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFC201UL, 8, data);
}

/* ── MC_Fault_Codes ── */
struct MC_Fault_Codes {
    uint64_t INV_Post_Fault_Lo : 16;
    uint64_t INV_Post_Fault_Hi : 16;
    uint64_t INV_Run_Fault_Lo : 16;
    uint64_t INV_Run_Fault_Hi : 16;
};

/**
 * @brief  Encode MC_Fault_Codes
 *         ID: 0x0CFFAB01  (218082049)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Post_Fault_Lo                        [scale=1, offset=0, unsigned, 16bit]
 * @param  INV_Post_Fault_Hi                        [scale=1, offset=0, unsigned, 16bit]
 * @param  INV_Run_Fault_Lo                         [scale=1, offset=0, unsigned, 16bit]
 * @param  INV_Run_Fault_Hi                         [scale=1, offset=0, unsigned, 16bit]
 */
void encode_MC_Fault_Codes(uint8_t data[8], uint64_t INV_Post_Fault_Lo, uint64_t INV_Post_Fault_Hi, uint64_t INV_Run_Fault_Lo, uint64_t INV_Run_Fault_Hi)
{
    struct MC_Fault_Codes frame = {0};

    frame.INV_Post_Fault_Lo = (uint64_t)(INV_Post_Fault_Lo);
    frame.INV_Post_Fault_Hi = (uint64_t)(INV_Post_Fault_Hi);
    frame.INV_Run_Fault_Lo = (uint64_t)(INV_Run_Fault_Lo);
    frame.INV_Run_Fault_Hi = (uint64_t)(INV_Run_Fault_Hi);
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Fault_Codes(uint64_t INV_Post_Fault_Lo, uint64_t INV_Post_Fault_Hi, uint64_t INV_Run_Fault_Lo, uint64_t INV_Run_Fault_Hi)
{
    uint8_t data[8];
    encode_MC_Fault_Codes(data, INV_Post_Fault_Lo, INV_Post_Fault_Hi, INV_Run_Fault_Lo, INV_Run_Fault_Hi);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFAB01UL, 8, data);
}

/* ── MC_Internal_States ── */
struct MC_Internal_States {
    uint64_t INV_VSM_State : 8;
    uint64_t INV_PWM_Frequency : 8;
    uint64_t INV_Inverter_State : 8;
    uint64_t INV_Relay_1_Status : 1;
    uint64_t INV_Relay_2_Status : 1;
    uint64_t INV_Relay_3_Status : 1;
    uint64_t INV_Relay_4_Status : 1;
    uint64_t INV_Relay_5_Status : 1;
    uint64_t INV_Relay_6_Status : 1;
    uint64_t FILLER_30 : 2;
    uint64_t INV_Inverter_Run_Mode : 1;
    uint64_t INV_Self_Sensing_Assist_Enable : 1;
    uint64_t FILLER_34 : 3;
    uint64_t INV_Inverter_Discharge_State : 3;
    uint64_t INV_Inverter_Command_Mode : 1;
    uint64_t FILLER_41 : 3;
    uint64_t INV_Rolling_Counter : 4;
    uint64_t INV_Inverter_Enable_State : 1;
    uint64_t INV_Burst_Model_Mode : 1;
    uint64_t FILLER_50 : 4;
    uint64_t INV_Key_Switch_Start_Status : 1;
    uint64_t INV_Inverter_Enable_Lockout : 1;
    uint64_t INV_Direction_Command : 1;
    uint64_t INV_BMS_Active : 1;
    uint64_t INV_BMS_Torque_Limiting : 1;
    uint64_t INV_Limit_Max_Speed : 1;
    uint64_t INV_Limit_Hot_Spot : 1;
    uint64_t INV_Low_Speed_Limiting : 1;
    uint64_t INV_Limit_Coolant_Derating : 1;
    uint64_t INV_Limit_Stall_Burst_Model : 1;
};

/**
 * @brief  Encode MC_Internal_States
 *         ID: 0x0CFFAA01  (218081793)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_VSM_State                            [scale=1, offset=0, unsigned, 8bit]
 * @param  INV_PWM_Frequency                        [scale=1, offset=0, unsigned, 8bit]
 * @param  INV_Inverter_State                       [scale=1, offset=0, unsigned, 8bit]
 * @param  INV_Relay_1_Status                       [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Relay_2_Status                       [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Relay_3_Status                       [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Relay_4_Status                       [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Relay_5_Status                       [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Relay_6_Status                       [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Inverter_Run_Mode                    [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Self_Sensing_Assist_Enable           [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Inverter_Discharge_State             [scale=1, offset=0, unsigned, 3bit]
 * @param  INV_Inverter_Command_Mode                [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Rolling_Counter                      [scale=1, offset=0, unsigned, 4bit]
 * @param  INV_Inverter_Enable_State                [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Burst_Model_Mode                     [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Key_Switch_Start_Status              [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Inverter_Enable_Lockout              [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Direction_Command                    [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_BMS_Active                           [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_BMS_Torque_Limiting                  [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Limit_Max_Speed                      [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Limit_Hot_Spot                       [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Low_Speed_Limiting                   [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Limit_Coolant_Derating               [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Limit_Stall_Burst_Model              [scale=1, offset=0, unsigned, 1bit]
 */
void encode_MC_Internal_States(uint8_t data[8], uint64_t INV_VSM_State, uint64_t INV_PWM_Frequency, uint64_t INV_Inverter_State, uint64_t INV_Relay_1_Status, uint64_t INV_Relay_2_Status, uint64_t INV_Relay_3_Status, uint64_t INV_Relay_4_Status, uint64_t INV_Relay_5_Status, uint64_t INV_Relay_6_Status, uint64_t INV_Inverter_Run_Mode, uint64_t INV_Self_Sensing_Assist_Enable, uint64_t INV_Inverter_Discharge_State, uint64_t INV_Inverter_Command_Mode, uint64_t INV_Rolling_Counter, uint64_t INV_Inverter_Enable_State, uint64_t INV_Burst_Model_Mode, uint64_t INV_Key_Switch_Start_Status, uint64_t INV_Inverter_Enable_Lockout, uint64_t INV_Direction_Command, uint64_t INV_BMS_Active, uint64_t INV_BMS_Torque_Limiting, uint64_t INV_Limit_Max_Speed, uint64_t INV_Limit_Hot_Spot, uint64_t INV_Low_Speed_Limiting, uint64_t INV_Limit_Coolant_Derating, uint64_t INV_Limit_Stall_Burst_Model)
{
    struct MC_Internal_States frame = {0};

    frame.INV_VSM_State = (uint64_t)(INV_VSM_State);
    frame.INV_PWM_Frequency = (uint64_t)(INV_PWM_Frequency);
    frame.INV_Inverter_State = (uint64_t)(INV_Inverter_State);
    frame.INV_Relay_1_Status = (uint64_t)(INV_Relay_1_Status);
    frame.INV_Relay_2_Status = (uint64_t)(INV_Relay_2_Status);
    frame.INV_Relay_3_Status = (uint64_t)(INV_Relay_3_Status);
    frame.INV_Relay_4_Status = (uint64_t)(INV_Relay_4_Status);
    frame.INV_Relay_5_Status = (uint64_t)(INV_Relay_5_Status);
    frame.INV_Relay_6_Status = (uint64_t)(INV_Relay_6_Status);
    frame.INV_Inverter_Run_Mode = (uint64_t)(INV_Inverter_Run_Mode);
    frame.INV_Self_Sensing_Assist_Enable = (uint64_t)(INV_Self_Sensing_Assist_Enable);
    frame.INV_Inverter_Discharge_State = (uint64_t)(INV_Inverter_Discharge_State);
    frame.INV_Inverter_Command_Mode = (uint64_t)(INV_Inverter_Command_Mode);
    frame.INV_Rolling_Counter = (uint64_t)(INV_Rolling_Counter);
    frame.INV_Inverter_Enable_State = (uint64_t)(INV_Inverter_Enable_State);
    frame.INV_Burst_Model_Mode = (uint64_t)(INV_Burst_Model_Mode);
    frame.INV_Key_Switch_Start_Status = (uint64_t)(INV_Key_Switch_Start_Status);
    frame.INV_Inverter_Enable_Lockout = (uint64_t)(INV_Inverter_Enable_Lockout);
    frame.INV_Direction_Command = (uint64_t)(INV_Direction_Command);
    frame.INV_BMS_Active = (uint64_t)(INV_BMS_Active);
    frame.INV_BMS_Torque_Limiting = (uint64_t)(INV_BMS_Torque_Limiting);
    frame.INV_Limit_Max_Speed = (uint64_t)(INV_Limit_Max_Speed);
    frame.INV_Limit_Hot_Spot = (uint64_t)(INV_Limit_Hot_Spot);
    frame.INV_Low_Speed_Limiting = (uint64_t)(INV_Low_Speed_Limiting);
    frame.INV_Limit_Coolant_Derating = (uint64_t)(INV_Limit_Coolant_Derating);
    frame.INV_Limit_Stall_Burst_Model = (uint64_t)(INV_Limit_Stall_Burst_Model);
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Internal_States(uint64_t INV_VSM_State, uint64_t INV_PWM_Frequency, uint64_t INV_Inverter_State, uint64_t INV_Relay_1_Status, uint64_t INV_Relay_2_Status, uint64_t INV_Relay_3_Status, uint64_t INV_Relay_4_Status, uint64_t INV_Relay_5_Status, uint64_t INV_Relay_6_Status, uint64_t INV_Inverter_Run_Mode, uint64_t INV_Self_Sensing_Assist_Enable, uint64_t INV_Inverter_Discharge_State, uint64_t INV_Inverter_Command_Mode, uint64_t INV_Rolling_Counter, uint64_t INV_Inverter_Enable_State, uint64_t INV_Burst_Model_Mode, uint64_t INV_Key_Switch_Start_Status, uint64_t INV_Inverter_Enable_Lockout, uint64_t INV_Direction_Command, uint64_t INV_BMS_Active, uint64_t INV_BMS_Torque_Limiting, uint64_t INV_Limit_Max_Speed, uint64_t INV_Limit_Hot_Spot, uint64_t INV_Low_Speed_Limiting, uint64_t INV_Limit_Coolant_Derating, uint64_t INV_Limit_Stall_Burst_Model)
{
    uint8_t data[8];
    encode_MC_Internal_States(data, INV_VSM_State, INV_PWM_Frequency, INV_Inverter_State, INV_Relay_1_Status, INV_Relay_2_Status, INV_Relay_3_Status, INV_Relay_4_Status, INV_Relay_5_Status, INV_Relay_6_Status, INV_Inverter_Run_Mode, INV_Self_Sensing_Assist_Enable, INV_Inverter_Discharge_State, INV_Inverter_Command_Mode, INV_Rolling_Counter, INV_Inverter_Enable_State, INV_Burst_Model_Mode, INV_Key_Switch_Start_Status, INV_Inverter_Enable_Lockout, INV_Direction_Command, INV_BMS_Active, INV_BMS_Torque_Limiting, INV_Limit_Max_Speed, INV_Limit_Hot_Spot, INV_Low_Speed_Limiting, INV_Limit_Coolant_Derating, INV_Limit_Stall_Burst_Model);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFAA01UL, 8, data);
}

/* ── MC_Internal_Voltages ── */
struct MC_Internal_Voltages {
    int64_t  INV_Ref_Voltage_1_5 : 16;
    int64_t  INV_Ref_Voltage_2_5 : 16;
    int64_t  INV_Ref_Voltage_5_0 : 16;
    int64_t  INV_Ref_Voltage_12_0 : 16;
};

/**
 * @brief  Encode MC_Internal_Voltages
 *         ID: 0x0CFFA901  (218081537)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Ref_Voltage_1_5                      [scale=0.01, offset=0, signed, 16bit]
 * @param  INV_Ref_Voltage_2_5                      [scale=0.01, offset=0, signed, 16bit]
 * @param  INV_Ref_Voltage_5_0                      [scale=0.01, offset=0, signed, 16bit]
 * @param  INV_Ref_Voltage_12_0                     [scale=0.01, offset=0, signed, 16bit]
 */
void encode_MC_Internal_Voltages(uint8_t data[8], float INV_Ref_Voltage_1_5, float INV_Ref_Voltage_2_5, float INV_Ref_Voltage_5_0, float INV_Ref_Voltage_12_0)
{
    struct MC_Internal_Voltages frame = {0};

    frame.INV_Ref_Voltage_1_5 = (int64_t)((INV_Ref_Voltage_1_5) / (0.01f));
    frame.INV_Ref_Voltage_2_5 = (int64_t)((INV_Ref_Voltage_2_5) / (0.01f));
    frame.INV_Ref_Voltage_5_0 = (int64_t)((INV_Ref_Voltage_5_0) / (0.01f));
    frame.INV_Ref_Voltage_12_0 = (int64_t)((INV_Ref_Voltage_12_0) / (0.01f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Internal_Voltages(float INV_Ref_Voltage_1_5, float INV_Ref_Voltage_2_5, float INV_Ref_Voltage_5_0, float INV_Ref_Voltage_12_0)
{
    uint8_t data[8];
    encode_MC_Internal_Voltages(data, INV_Ref_Voltage_1_5, INV_Ref_Voltage_2_5, INV_Ref_Voltage_5_0, INV_Ref_Voltage_12_0);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA901UL, 8, data);
}

/* ── MC_Flux_ID_IQ_Info ── */
struct MC_Flux_ID_IQ_Info {
    int64_t  INV_Vd_ff : 16;
    int64_t  INV_Vq_ff : 16;
    int64_t  INV_Id : 16;
    int64_t  INV_Iq : 16;
};

/**
 * @brief  Encode MC_Flux_ID_IQ_Info
 *         ID: 0x0CFFA801  (218081281)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Vd_ff                                [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Vq_ff                                [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Id                                   [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Iq                                   [scale=0.1, offset=0, signed, 16bit]
 */
void encode_MC_Flux_ID_IQ_Info(uint8_t data[8], float INV_Vd_ff, float INV_Vq_ff, float INV_Id, float INV_Iq)
{
    struct MC_Flux_ID_IQ_Info frame = {0};

    frame.INV_Vd_ff = (int64_t)((INV_Vd_ff) / (0.1f));
    frame.INV_Vq_ff = (int64_t)((INV_Vq_ff) / (0.1f));
    frame.INV_Id = (int64_t)((INV_Id) / (0.1f));
    frame.INV_Iq = (int64_t)((INV_Iq) / (0.1f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Flux_ID_IQ_Info(float INV_Vd_ff, float INV_Vq_ff, float INV_Id, float INV_Iq)
{
    uint8_t data[8];
    encode_MC_Flux_ID_IQ_Info(data, INV_Vd_ff, INV_Vq_ff, INV_Id, INV_Iq);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA801UL, 8, data);
}

/* ── MC_Voltage_Info ── */
struct MC_Voltage_Info {
    int64_t  INV_DC_Bus_Voltage : 16;
    int64_t  INV_Output_Voltage : 16;
    int64_t  INV_VAB_Vd_Voltage : 16;
    int64_t  INV_VBC_Vq_Voltage : 16;
};

/**
 * @brief  Encode MC_Voltage_Info
 *         ID: 0x0CFFA701  (218081025)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_DC_Bus_Voltage                       [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Output_Voltage                       [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_VAB_Vd_Voltage                       [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_VBC_Vq_Voltage                       [scale=0.1, offset=0, signed, 16bit]
 */
void encode_MC_Voltage_Info(uint8_t data[8], float INV_DC_Bus_Voltage, float INV_Output_Voltage, float INV_VAB_Vd_Voltage, float INV_VBC_Vq_Voltage)
{
    struct MC_Voltage_Info frame = {0};

    frame.INV_DC_Bus_Voltage = (int64_t)((INV_DC_Bus_Voltage) / (0.1f));
    frame.INV_Output_Voltage = (int64_t)((INV_Output_Voltage) / (0.1f));
    frame.INV_VAB_Vd_Voltage = (int64_t)((INV_VAB_Vd_Voltage) / (0.1f));
    frame.INV_VBC_Vq_Voltage = (int64_t)((INV_VBC_Vq_Voltage) / (0.1f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Voltage_Info(float INV_DC_Bus_Voltage, float INV_Output_Voltage, float INV_VAB_Vd_Voltage, float INV_VBC_Vq_Voltage)
{
    uint8_t data[8];
    encode_MC_Voltage_Info(data, INV_DC_Bus_Voltage, INV_Output_Voltage, INV_VAB_Vd_Voltage, INV_VBC_Vq_Voltage);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA701UL, 8, data);
}

/* ── MC_Current_Info ── */
struct MC_Current_Info {
    int64_t  INV_Phase_A_Current : 16;
    int64_t  INV_Phase_B_Current : 16;
    int64_t  INV_Phase_C_Current : 16;
    int64_t  INV_DC_Bus_Current : 16;
};

/**
 * @brief  Encode MC_Current_Info
 *         ID: 0x0CFFA601  (218080769)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Phase_A_Current                      [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Phase_B_Current                      [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Phase_C_Current                      [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_DC_Bus_Current                       [scale=0.1, offset=0, signed, 16bit]
 */
void encode_MC_Current_Info(uint8_t data[8], float INV_Phase_A_Current, float INV_Phase_B_Current, float INV_Phase_C_Current, float INV_DC_Bus_Current)
{
    struct MC_Current_Info frame = {0};

    frame.INV_Phase_A_Current = (int64_t)((INV_Phase_A_Current) / (0.1f));
    frame.INV_Phase_B_Current = (int64_t)((INV_Phase_B_Current) / (0.1f));
    frame.INV_Phase_C_Current = (int64_t)((INV_Phase_C_Current) / (0.1f));
    frame.INV_DC_Bus_Current = (int64_t)((INV_DC_Bus_Current) / (0.1f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Current_Info(float INV_Phase_A_Current, float INV_Phase_B_Current, float INV_Phase_C_Current, float INV_DC_Bus_Current)
{
    uint8_t data[8];
    encode_MC_Current_Info(data, INV_Phase_A_Current, INV_Phase_B_Current, INV_Phase_C_Current, INV_DC_Bus_Current);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA601UL, 8, data);
}

/* ── MC_Motor_Position_Info ── */
struct MC_Motor_Position_Info {
    uint64_t INV_Motor_Angle_Electrical : 16;
    int64_t  INV_Motor_Speed : 16;
    int64_t  INV_Electrical_Output_Frequency : 16;
    int64_t  INV_Delta_Resolver_Filtered : 16;
};

/**
 * @brief  Encode MC_Motor_Position_Info
 *         ID: 0x0CFFA501  (218080513)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Motor_Angle_Electrical               [scale=0.1, offset=0, unsigned, 16bit]
 * @param  INV_Motor_Speed                          [scale=1, offset=0, signed, 16bit]
 * @param  INV_Electrical_Output_Frequency          [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Delta_Resolver_Filtered              [scale=0.1, offset=0, signed, 16bit]
 */
void encode_MC_Motor_Position_Info(uint8_t data[8], float INV_Motor_Angle_Electrical, int64_t INV_Motor_Speed, float INV_Electrical_Output_Frequency, float INV_Delta_Resolver_Filtered)
{
    struct MC_Motor_Position_Info frame = {0};

    frame.INV_Motor_Angle_Electrical = (uint64_t)((INV_Motor_Angle_Electrical) / (0.1f));
    frame.INV_Motor_Speed = (int64_t)(INV_Motor_Speed);
    frame.INV_Electrical_Output_Frequency = (int64_t)((INV_Electrical_Output_Frequency) / (0.1f));
    frame.INV_Delta_Resolver_Filtered = (int64_t)((INV_Delta_Resolver_Filtered) / (0.1f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Motor_Position_Info(float INV_Motor_Angle_Electrical, int64_t INV_Motor_Speed, float INV_Electrical_Output_Frequency, float INV_Delta_Resolver_Filtered)
{
    uint8_t data[8];
    encode_MC_Motor_Position_Info(data, INV_Motor_Angle_Electrical, INV_Motor_Speed, INV_Electrical_Output_Frequency, INV_Delta_Resolver_Filtered);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA501UL, 8, data);
}

/* ── MC_Digital_Input_Status ── */
struct MC_Digital_Input_Status {
    uint64_t INV_Digital_Input_1 : 1;
    uint64_t FILLER_1 : 7;
    uint64_t INV_Digital_Input_2 : 1;
    uint64_t FILLER_9 : 7;
    uint64_t INV_Digital_Input_3 : 1;
    uint64_t FILLER_17 : 7;
    uint64_t INV_Digital_Input_4 : 1;
    uint64_t FILLER_25 : 7;
    uint64_t INV_Digital_Input_5 : 1;
    uint64_t FILLER_33 : 7;
    uint64_t INV_Digital_Input_6 : 1;
    uint64_t FILLER_41 : 7;
    uint64_t INV_Digital_Input_7 : 1;
    uint64_t FILLER_49 : 7;
    uint64_t INV_Digital_Input_8 : 1;
    uint64_t FILLER_END : 7;
};

/**
 * @brief  Encode MC_Digital_Input_Status
 *         ID: 0x0CFFA401  (218080257)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Digital_Input_1                      [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Digital_Input_2                      [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Digital_Input_3                      [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Digital_Input_4                      [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Digital_Input_5                      [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Digital_Input_6                      [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Digital_Input_7                      [scale=1, offset=0, unsigned, 1bit]
 * @param  INV_Digital_Input_8                      [scale=1, offset=0, unsigned, 1bit]
 */
void encode_MC_Digital_Input_Status(uint8_t data[8], uint64_t INV_Digital_Input_1, uint64_t INV_Digital_Input_2, uint64_t INV_Digital_Input_3, uint64_t INV_Digital_Input_4, uint64_t INV_Digital_Input_5, uint64_t INV_Digital_Input_6, uint64_t INV_Digital_Input_7, uint64_t INV_Digital_Input_8)
{
    struct MC_Digital_Input_Status frame = {0};

    frame.INV_Digital_Input_1 = (uint64_t)(INV_Digital_Input_1);
    frame.INV_Digital_Input_2 = (uint64_t)(INV_Digital_Input_2);
    frame.INV_Digital_Input_3 = (uint64_t)(INV_Digital_Input_3);
    frame.INV_Digital_Input_4 = (uint64_t)(INV_Digital_Input_4);
    frame.INV_Digital_Input_5 = (uint64_t)(INV_Digital_Input_5);
    frame.INV_Digital_Input_6 = (uint64_t)(INV_Digital_Input_6);
    frame.INV_Digital_Input_7 = (uint64_t)(INV_Digital_Input_7);
    frame.INV_Digital_Input_8 = (uint64_t)(INV_Digital_Input_8);
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Digital_Input_Status(uint64_t INV_Digital_Input_1, uint64_t INV_Digital_Input_2, uint64_t INV_Digital_Input_3, uint64_t INV_Digital_Input_4, uint64_t INV_Digital_Input_5, uint64_t INV_Digital_Input_6, uint64_t INV_Digital_Input_7, uint64_t INV_Digital_Input_8)
{
    uint8_t data[8];
    encode_MC_Digital_Input_Status(data, INV_Digital_Input_1, INV_Digital_Input_2, INV_Digital_Input_3, INV_Digital_Input_4, INV_Digital_Input_5, INV_Digital_Input_6, INV_Digital_Input_7, INV_Digital_Input_8);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA401UL, 8, data);
}

/* ── MC_Analog_Input_Voltages ── */
struct MC_Analog_Input_Voltages {
    uint64_t INV_Analog_Input_1 : 10;
    uint64_t INV_Analog_Input_2 : 10;
    uint64_t INV_Analog_Input_3 : 10;
    uint64_t FILLER_30 : 2;
    uint64_t INV_Analog_Input_4 : 10;
    uint64_t INV_Analog_Input_5 : 10;
    uint64_t INV_Analog_Input_6 : 10;
    uint64_t FILLER_END : 2;
};

/**
 * @brief  Encode MC_Analog_Input_Voltages
 *         ID: 0x0CFFA301  (218080001)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Analog_Input_1                       [scale=0.01, offset=0, unsigned, 10bit]
 * @param  INV_Analog_Input_2                       [scale=0.01, offset=0, unsigned, 10bit]
 * @param  INV_Analog_Input_3                       [scale=0.01, offset=0, unsigned, 10bit]
 * @param  INV_Analog_Input_4                       [scale=0.01, offset=0, unsigned, 10bit]
 * @param  INV_Analog_Input_5                       [scale=0.01, offset=0, unsigned, 10bit]
 * @param  INV_Analog_Input_6                       [scale=0.01, offset=0, unsigned, 10bit]
 */
void encode_MC_Analog_Input_Voltages(uint8_t data[8], float INV_Analog_Input_1, float INV_Analog_Input_2, float INV_Analog_Input_3, float INV_Analog_Input_4, float INV_Analog_Input_5, float INV_Analog_Input_6)
{
    struct MC_Analog_Input_Voltages frame = {0};

    frame.INV_Analog_Input_1 = (uint64_t)((INV_Analog_Input_1) / (0.01f));
    frame.INV_Analog_Input_2 = (uint64_t)((INV_Analog_Input_2) / (0.01f));
    frame.INV_Analog_Input_3 = (uint64_t)((INV_Analog_Input_3) / (0.01f));
    frame.INV_Analog_Input_4 = (uint64_t)((INV_Analog_Input_4) / (0.01f));
    frame.INV_Analog_Input_5 = (uint64_t)((INV_Analog_Input_5) / (0.01f));
    frame.INV_Analog_Input_6 = (uint64_t)((INV_Analog_Input_6) / (0.01f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Analog_Input_Voltages(float INV_Analog_Input_1, float INV_Analog_Input_2, float INV_Analog_Input_3, float INV_Analog_Input_4, float INV_Analog_Input_5, float INV_Analog_Input_6)
{
    uint8_t data[8];
    encode_MC_Analog_Input_Voltages(data, INV_Analog_Input_1, INV_Analog_Input_2, INV_Analog_Input_3, INV_Analog_Input_4, INV_Analog_Input_5, INV_Analog_Input_6);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA301UL, 8, data);
}

/* ── MC_Temperature_Set_3 ── */
struct MC_Temperature_Set_3 {
    int64_t  INV_Coolant_Temp : 16;
    int64_t  INV_Hot_Spot_Temp : 16;
    int64_t  INV_Motor_Temp : 16;
    int64_t  INV_Torque_Shudder : 16;
};

/**
 * @brief  Encode MC_Temperature_Set_3
 *         ID: 0x0CFFA201  (218079745)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Coolant_Temp                         [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Hot_Spot_Temp                        [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Motor_Temp                           [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Torque_Shudder                       [scale=0.1, offset=0, signed, 16bit]
 */
void encode_MC_Temperature_Set_3(uint8_t data[8], float INV_Coolant_Temp, float INV_Hot_Spot_Temp, float INV_Motor_Temp, float INV_Torque_Shudder)
{
    struct MC_Temperature_Set_3 frame = {0};

    frame.INV_Coolant_Temp = (int64_t)((INV_Coolant_Temp) / (0.1f));
    frame.INV_Hot_Spot_Temp = (int64_t)((INV_Hot_Spot_Temp) / (0.1f));
    frame.INV_Motor_Temp = (int64_t)((INV_Motor_Temp) / (0.1f));
    frame.INV_Torque_Shudder = (int64_t)((INV_Torque_Shudder) / (0.1f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Temperature_Set_3(float INV_Coolant_Temp, float INV_Hot_Spot_Temp, float INV_Motor_Temp, float INV_Torque_Shudder)
{
    uint8_t data[8];
    encode_MC_Temperature_Set_3(data, INV_Coolant_Temp, INV_Hot_Spot_Temp, INV_Motor_Temp, INV_Torque_Shudder);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA201UL, 8, data);
}

/* ── MC_Temperature_Set_2 ── */
struct MC_Temperature_Set_2 {
    int64_t  INV_Control_Board_Temp : 16;
    int64_t  INV_RTD1_Temperature : 16;
    int64_t  INV_RTD2_Temperature : 16;
    int64_t  INV_Stall_Burst_Model_Temp : 16;
};

/**
 * @brief  Encode MC_Temperature_Set_2
 *         ID: 0x0CFFA101  (218079489)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Control_Board_Temp                   [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_RTD1_Temperature                     [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_RTD2_Temperature                     [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Stall_Burst_Model_Temp               [scale=0.1, offset=0, signed, 16bit]
 */
void encode_MC_Temperature_Set_2(uint8_t data[8], float INV_Control_Board_Temp, float INV_RTD1_Temperature, float INV_RTD2_Temperature, float INV_Stall_Burst_Model_Temp)
{
    struct MC_Temperature_Set_2 frame = {0};

    frame.INV_Control_Board_Temp = (int64_t)((INV_Control_Board_Temp) / (0.1f));
    frame.INV_RTD1_Temperature = (int64_t)((INV_RTD1_Temperature) / (0.1f));
    frame.INV_RTD2_Temperature = (int64_t)((INV_RTD2_Temperature) / (0.1f));
    frame.INV_Stall_Burst_Model_Temp = (int64_t)((INV_Stall_Burst_Model_Temp) / (0.1f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Temperature_Set_2(float INV_Control_Board_Temp, float INV_RTD1_Temperature, float INV_RTD2_Temperature, float INV_Stall_Burst_Model_Temp)
{
    uint8_t data[8];
    encode_MC_Temperature_Set_2(data, INV_Control_Board_Temp, INV_RTD1_Temperature, INV_RTD2_Temperature, INV_Stall_Burst_Model_Temp);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA101UL, 8, data);
}

/* ── MC_Temperature_Set_1 ── */
struct MC_Temperature_Set_1 {
    int64_t  INV_Module_A_Temp : 16;
    int64_t  INV_Module_B_Temp : 16;
    int64_t  INV_Module_C_Temp : 16;
    int64_t  INV_Gate_Driver_Board_Temp : 16;
};

/**
 * @brief  Encode MC_Temperature_Set_1
 *         ID: 0x0CFFA001  (218079233)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Module_A_Temp                        [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Module_B_Temp                        [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Module_C_Temp                        [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Gate_Driver_Board_Temp               [scale=0.1, offset=0, signed, 16bit]
 */
void encode_MC_Temperature_Set_1(uint8_t data[8], float INV_Module_A_Temp, float INV_Module_B_Temp, float INV_Module_C_Temp, float INV_Gate_Driver_Board_Temp)
{
    struct MC_Temperature_Set_1 frame = {0};

    frame.INV_Module_A_Temp = (int64_t)((INV_Module_A_Temp) / (0.1f));
    frame.INV_Module_B_Temp = (int64_t)((INV_Module_B_Temp) / (0.1f));
    frame.INV_Module_C_Temp = (int64_t)((INV_Module_C_Temp) / (0.1f));
    frame.INV_Gate_Driver_Board_Temp = (int64_t)((INV_Gate_Driver_Board_Temp) / (0.1f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Temperature_Set_1(float INV_Module_A_Temp, float INV_Module_B_Temp, float INV_Module_C_Temp, float INV_Gate_Driver_Board_Temp)
{
    uint8_t data[8];
    encode_MC_Temperature_Set_1(data, INV_Module_A_Temp, INV_Module_B_Temp, INV_Module_C_Temp, INV_Gate_Driver_Board_Temp);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFA001UL, 8, data);
}

/* ── MC_Firmware_Info ── */
struct MC_Firmware_Info {
    uint64_t INV_Project_Code_EEP_Ver : 16;
    uint64_t INV_SW_Version : 16;
    uint64_t INV_DateCode_MMDD : 16;
    uint64_t INV_DateCode_YYYY : 16;
};

/**
 * @brief  Encode MC_Firmware_Info
 *         ID: 0x0CFFAE01  (218082817)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Project_Code_EEP_Ver                 [scale=1, offset=0, unsigned, 16bit]
 * @param  INV_SW_Version                           [scale=1, offset=0, unsigned, 16bit]
 * @param  INV_DateCode_MMDD                        [scale=1, offset=0, unsigned, 16bit]
 * @param  INV_DateCode_YYYY                        [scale=1, offset=0, unsigned, 16bit]
 */
void encode_MC_Firmware_Info(uint8_t data[8], uint64_t INV_Project_Code_EEP_Ver, uint64_t INV_SW_Version, uint64_t INV_DateCode_MMDD, uint64_t INV_DateCode_YYYY)
{
    struct MC_Firmware_Info frame = {0};

    frame.INV_Project_Code_EEP_Ver = (uint64_t)(INV_Project_Code_EEP_Ver);
    frame.INV_SW_Version = (uint64_t)(INV_SW_Version);
    frame.INV_DateCode_MMDD = (uint64_t)(INV_DateCode_MMDD);
    frame.INV_DateCode_YYYY = (uint64_t)(INV_DateCode_YYYY);
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Firmware_Info(uint64_t INV_Project_Code_EEP_Ver, uint64_t INV_SW_Version, uint64_t INV_DateCode_MMDD, uint64_t INV_DateCode_YYYY)
{
    uint8_t data[8];
    encode_MC_Firmware_Info(data, INV_Project_Code_EEP_Ver, INV_SW_Version, INV_DateCode_MMDD, INV_DateCode_YYYY);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFAE01UL, 8, data);
}

/* ── MC_Fast_Info ── */
struct MC_Fast_Info {
    int64_t  INV_Fast_Torque_Command : 16;
    int64_t  INV_Fast_Torque_Feedback : 16;
    int64_t  INV_Fast_Motor_Speed : 16;
    int64_t  INV_Fast_DC_Bus_Voltage : 16;
};

/**
 * @brief  Encode MC_Fast_Info
 *         ID: 0x0CFFB001  (218083329)  Length: 8B
 * @param  data  Output buffer, must be >= 8 bytes
 * @param  INV_Fast_Torque_Command                  [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Fast_Torque_Feedback                 [scale=0.1, offset=0, signed, 16bit]
 * @param  INV_Fast_Motor_Speed                     [scale=1, offset=0, signed, 16bit]
 * @param  INV_Fast_DC_Bus_Voltage                  [scale=0.1, offset=0, signed, 16bit]
 */
void encode_MC_Fast_Info(uint8_t data[8], float INV_Fast_Torque_Command, float INV_Fast_Torque_Feedback, int64_t INV_Fast_Motor_Speed, float INV_Fast_DC_Bus_Voltage)
{
    struct MC_Fast_Info frame = {0};

    frame.INV_Fast_Torque_Command = (int64_t)((INV_Fast_Torque_Command) / (0.1f));
    frame.INV_Fast_Torque_Feedback = (int64_t)((INV_Fast_Torque_Feedback) / (0.1f));
    frame.INV_Fast_Motor_Speed = (int64_t)(INV_Fast_Motor_Speed);
    frame.INV_Fast_DC_Bus_Voltage = (int64_t)((INV_Fast_DC_Bus_Voltage) / (0.1f));
    memcpy(data, &frame, 8);
}

int sendCAN_MC_Fast_Info(float INV_Fast_Torque_Command, float INV_Fast_Torque_Feedback, int64_t INV_Fast_Motor_Speed, float INV_Fast_DC_Bus_Voltage)
{
    uint8_t data[8];
    encode_MC_Fast_Info(data, INV_Fast_Torque_Command, INV_Fast_Torque_Feedback, INV_Fast_Motor_Speed, INV_Fast_DC_Bus_Voltage);
    return HIL_CAN_Transmit(&hcan3, 0x0CFFB001UL, 8, data);
}

