#ifndef CAN_SIGNALS_H
#define CAN_SIGNALS_H

/* Auto-generated by generate_can_signals.py — do not edit manually. */
/* Re-run after any DBC change and commit the output.                */

#include <stdint.h>
#include <string.h>
#include "can.h"        /* hcan3 */

/* ── Message ID defines ───────────────────────────────────────────── */
#define CAN_ID_WSBFL_BRAKEPRESSURE                                0x04120208UL  /* 68289032 */
#define CAN_ID_WSBRR_SPEED                                        0x0400020BUL  /* 67109387 */
#define CAN_ID_WSBRL_SPEED                                        0x0400020AUL  /* 67109386 */
#define CAN_ID_PDU_CAR_STATE                                      0x0BAAFF03UL  /* 195755779 */
#define CAN_ID_TRACTIONCONTROLCONFIG                              0x080302C0UL  /* 134415040 */
#define CAN_ID_UARTOVERCANTX                                      0x0406FF02UL  /* 67567362 */
#define CAN_ID_UARTOVERCANCONFIG                                  0x0405FF02UL  /* 67501826 */
#define CAN_ID_WSBFR_SENSORS                                      0x04100209UL  /* 68157961 */
#define CAN_ID_WSBFL_SENSORS                                      0x04100208UL  /* 68157960 */
#define CAN_ID_PRECHARGESTATE                                     0x08D4FF01UL  /* 148176641 */
#define CAN_ID_DCU_HEARTBEAT                                      0x0404FF07UL  /* 67436295 */
#define CAN_ID_PDU_HEARTBEAT                                      0x0404FF03UL  /* 67436291 */
#define CAN_ID_BMU_HEARTBEAT                                      0x0404FF01UL  /* 67436289 */
#define CAN_ID_BMU_HV_POWER_STATE                                 0x0425FF01UL  /* 69598977 */
#define CAN_ID_PDU_DTC                                            0x0000FF03UL  /* 65283 */
#define CAN_ID_DCU_DTC                                            0x0000FF07UL  /* 65287 */
#define CAN_ID_BMU_DTC                                            0x0000FF01UL  /* 65281 */
#define CAN_ID_CHARGECART_DTC                                     0x0000FF04UL  /* 65284 */
#define CAN_ID_TEMPCOOLANTRIGHT                                   0x18000213UL  /* 402653715 */
#define CAN_ID_TEMPCOOLANTLEFT                                    0x18000212UL  /* 402653714 */
#define CAN_ID_BMU_STATEBATTERYHV                                 0x08000201UL  /* 134218241 */
#define CAN_ID_PDU_CHANNELSTATUS                                  0x04060203UL  /* 67502595 */
#define CAN_ID_BMU_BATTERYSTATUSHV                                0x08041001UL  /* 134483969 */
#define CAN_ID_BMU_STATEBUSHV                                     0x08101201UL  /* 135270913 */
#define CAN_ID_MC_MODULATION_AND_FLUX_INFO                        0x0CFFAD01UL  /* 218082561 */
#define CAN_ID_MC_TORQUE_AND_TIMER_INFO                           0x0CFFAC01UL  /* 218082305 */
#define CAN_ID_MC_READ_WRITE_PARAM_RESPONSE                       0x0CFFC201UL  /* 218087937 */
#define CAN_ID_MC_FAULT_CODES                                     0x0CFFAB01UL  /* 218082049 */
#define CAN_ID_MC_INTERNAL_STATES                                 0x0CFFAA01UL  /* 218081793 */
#define CAN_ID_MC_INTERNAL_VOLTAGES                               0x0CFFA901UL  /* 218081537 */
#define CAN_ID_MC_FLUX_ID_IQ_INFO                                 0x0CFFA801UL  /* 218081281 */
#define CAN_ID_MC_VOLTAGE_INFO                                    0x0CFFA701UL  /* 218081025 */
#define CAN_ID_MC_CURRENT_INFO                                    0x0CFFA601UL  /* 218080769 */
#define CAN_ID_MC_MOTOR_POSITION_INFO                             0x0CFFA501UL  /* 218080513 */
#define CAN_ID_MC_DIGITAL_INPUT_STATUS                            0x0CFFA401UL  /* 218080257 */
#define CAN_ID_MC_ANALOG_INPUT_VOLTAGES                           0x0CFFA301UL  /* 218080001 */
#define CAN_ID_MC_TEMPERATURE_SET_3                               0x0CFFA201UL  /* 218079745 */
#define CAN_ID_MC_TEMPERATURE_SET_2                               0x0CFFA101UL  /* 218079489 */
#define CAN_ID_MC_TEMPERATURE_SET_1                               0x0CFFA001UL  /* 218079233 */
#define CAN_ID_MC_FIRMWARE_INFO                                   0x0CFFAE01UL  /* 218082817 */
#define CAN_ID_MC_FAST_INFO                                       0x0CFFB001UL  /* 218083329 */

/* ── Value table enums ────────────────────────────────────────────── */
typedef enum {
    HV_Power_State_Off = 0,
    HV_Power_State_On = 1,
} HV_Power_State_Values;

typedef enum {
    StatusPowerInverter_INVALID = 0,
    StatusPowerInverter_CHANNEL_OFF = 1,
    StatusPowerInverter_CHANNEL_ON = 2,
    StatusPowerInverter_CHANNEL_OFF_FUSE_BLOWN = 3,
    StatusPowerInverter_CHANNEL_ON_FUSE_BLOWN = 4,
} StatusPowerInverter_Values;

typedef enum {
    StatusPowerRadiator_INVALID = 0,
    StatusPowerRadiator_CHANNEL_OFF = 1,
    StatusPowerRadiator_CHANNEL_ON = 2,
    StatusPowerRadiator_CHANNEL_OFF_FUSE_BLOWN = 3,
    StatusPowerRadiator_CHANNEL_ON_FUSE_BLOWN = 4,
} StatusPowerRadiator_Values;

typedef enum {
    StateBMS_Self_Check = 0,
    StateBMS_Wait_System_Up = 1,
    StateBMS_HV_Disable = 2,
    StateBMS_HV_Enable = 3,
    StateBMS_Precharge = 4,
    StateBMS_Discharge = 5,
    StateBMS_Charging = 6,
    StateBMS_Failure_Fatal = 7,
} StateBMS_Values;

typedef enum {
    INV_VSM_State_START_STATE = 0,
    INV_VSM_State_PRECHARGE_INIT_STATE = 1,
    INV_VSM_State_PRECHARGE_ACTIVE_STATE = 2,
    INV_VSM_State_PRECHARGE_COMPLETE_STATE = 3,
    INV_VSM_State_WAIT_STATE = 4,
    INV_VSM_State_READY_STATE = 5,
    INV_VSM_State_MOTOR_RUNNING_STATE = 6,
    INV_VSM_State_FAULT_STATE = 7,
    INV_VSM_State_SHUTDOWN_IN_PROGRESS_KEY_SWITCH = 14,
    INV_VSM_State_RECYCLE_POWER = 15,
} INV_VSM_State_Values;

typedef enum {
    INV_Inverter_State_Power_up = 0,
    INV_Inverter_State_Stop = 1,
    INV_Inverter_State_Open_Loop = 2,
    INV_Inverter_State_Closed_Loop = 3,
    INV_Inverter_State_Internal_State_4 = 4,
    INV_Inverter_State_Internal_State_5 = 5,
    INV_Inverter_State_Internal_State_6 = 6,
    INV_Inverter_State_Internal_State_7 = 7,
    INV_Inverter_State_Idle_Run = 8,
    INV_Inverter_State_Idle_Stop = 9,
    INV_Inverter_State_Internal_State_A = 10,
    INV_Inverter_State_Intern_State = 11,
    INV_Inverter_State_Internal_State_C = 12,
} INV_Inverter_State_Values;

typedef enum {
    INV_Inverter_Discharge_State_Disabled = 0,
    INV_Inverter_Discharge_State_Enabled = 1,
    INV_Inverter_Discharge_State_Speed_Check = 2,
    INV_Inverter_Discharge_State_Active = 3,
    INV_Inverter_Discharge_State_Complete = 4,
    INV_Inverter_Discharge_State_Error = 5,
    INV_Inverter_Discharge_State_Override = 6,
    INV_Inverter_Discharge_State_Timeout = 7,
} INV_Inverter_Discharge_State_Values;

typedef enum {
    INV_Burst_Model_Mode_Stall = 0,
    INV_Burst_Model_Mode_High_Speed = 1,
} INV_Burst_Model_Mode_Values;

typedef enum {
    INV_Limit_Stall_Burst_Model_Not_Limiting = 0,
    INV_Limit_Stall_Burst_Model_Limiting = 1,
} INV_Limit_Stall_Burst_Model_Values;

/* ── Function prototypes ──────────────────────────────────────────── */
#ifdef __cplusplus
extern "C" {
#endif

void encode_WSBFL_BrakePressure(uint8_t data[8], int64_t RearBrakePressure);
int sendCAN_WSBFL_BrakePressure(int64_t RearBrakePressure);

void encode_WSBRR_Speed(uint8_t data[8], float RRSpeedKPH, uint64_t RRSpeedRPM);
int sendCAN_WSBRR_Speed(float RRSpeedKPH, uint64_t RRSpeedRPM);

void encode_WSBRL_Speed(uint8_t data[6], float RLSpeedKPH, int64_t RLSpeedRPM);
int sendCAN_WSBRL_Speed(float RLSpeedKPH, int64_t RLSpeedRPM);

void encode_PDU_Car_State(uint8_t data[8], int64_t CarStateIsLV, int64_t CarStateIsEM, int64_t CarStateIsHV);
int sendCAN_PDU_Car_State(int64_t CarStateIsLV, int64_t CarStateIsEM, int64_t CarStateIsHV);

void encode_TractionControlConfig(uint8_t data[8], float TC_kP, float TC_kI, float TC_kD, float TC_desiredSlipPercent);
int sendCAN_TractionControlConfig(float TC_kP, float TC_kI, float TC_kD, float TC_desiredSlipPercent);

void encode_UartOverCanTx(uint8_t data[1], int64_t UartOverCanTX);
int sendCAN_UartOverCanTx(int64_t UartOverCanTX);

void encode_UartOverCanConfig(uint8_t data[1], int64_t UartOverCanConfigSignal);
int sendCAN_UartOverCanConfig(int64_t UartOverCanConfigSignal);

void encode_WSBFR_Sensors(uint8_t data[8], uint64_t FR_WheelDistance, float FR_Speed_RAD_S);
int sendCAN_WSBFR_Sensors(uint64_t FR_WheelDistance, float FR_Speed_RAD_S);

void encode_WSBFL_Sensors(uint8_t data[8], uint64_t FL_WheelDistance, float FL_Speed_RAD_S);
int sendCAN_WSBFL_Sensors(uint64_t FL_WheelDistance, float FL_Speed_RAD_S);

void encode_PrechargeState(uint8_t data[8], uint64_t PrechargeState);
int sendCAN_PrechargeState(uint64_t PrechargeState);

void encode_DCU_Heartbeat(uint8_t data[1], int64_t DCU_Heartbeat_dummydata);
int sendCAN_DCU_Heartbeat(int64_t DCU_Heartbeat_dummydata);

void encode_PDU_Heartbeat(uint8_t data[1], int64_t PDU_Heartbeat_dummydata);
int sendCAN_PDU_Heartbeat(int64_t PDU_Heartbeat_dummydata);

void encode_BMU_Heartbeat(uint8_t data[1], int64_t BMU_Heartbeat_dummydata);
int sendCAN_BMU_Heartbeat(int64_t BMU_Heartbeat_dummydata);

void encode_BMU_HV_Power_State(uint8_t data[1], uint64_t HV_Power_State);
int sendCAN_BMU_HV_Power_State(uint64_t HV_Power_State);

void encode_PDU_DTC(uint8_t data[6], uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data);
int sendCAN_PDU_DTC(uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data);

void encode_DCU_DTC(uint8_t data[6], uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data);
int sendCAN_DCU_DTC(uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data);

void encode_BMU_DTC(uint8_t data[6], uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data);
int sendCAN_BMU_DTC(uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data);

void encode_ChargeCart_DTC(uint8_t data[6], uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data);
int sendCAN_ChargeCart_DTC(uint64_t DTC_CODE, int64_t DTC_Severity, int64_t DTC_Data);

void encode_TempCoolantRight(uint8_t data[8], float TempInletRadMotorRight, float TempOutletRadMotorRight);
int sendCAN_TempCoolantRight(float TempInletRadMotorRight, float TempOutletRadMotorRight);

void encode_TempCoolantLeft(uint8_t data[8], float TempInletRadMotorLeft, float TempOutletRadMotorLeft);
int sendCAN_TempCoolantLeft(float TempInletRadMotorLeft, float TempOutletRadMotorLeft);

void encode_BMU_stateBatteryHV(uint8_t data[8], uint64_t VoltageBatteryHV, float CurrentDCBatteryHV, float PowerBatteryHV);
int sendCAN_BMU_stateBatteryHV(uint64_t VoltageBatteryHV, float CurrentDCBatteryHV, float PowerBatteryHV);

void encode_PDU_ChannelStatus(uint8_t data[7], int64_t StatusPowerInverter, int64_t StatusPowerRadiator);
int sendCAN_PDU_ChannelStatus(int64_t StatusPowerInverter, int64_t StatusPowerRadiator);

void encode_BMU_batteryStatusHV(uint8_t data[8], float StateBatteryChargeHV, float StateBatteryHealthHV, float StateBatteryPowerHV, int64_t StateBMS);
int sendCAN_BMU_batteryStatusHV(float StateBatteryChargeHV, float StateBatteryHealthHV, float StateBatteryPowerHV, int64_t StateBMS);

void encode_BMU_stateBusHV(uint8_t data[8], float VoltageBusHV);
int sendCAN_BMU_stateBusHV(float VoltageBusHV);

void encode_MC_Modulation_And_Flux_Info(uint8_t data[8], float INV_Modulation_Index, float INV_Flux_Weakening_Output, float INV_Id_Command, float INV_Iq_Command);
int sendCAN_MC_Modulation_And_Flux_Info(float INV_Modulation_Index, float INV_Flux_Weakening_Output, float INV_Id_Command, float INV_Iq_Command);

void encode_MC_Torque_And_Timer_Info(uint8_t data[8], float INV_Commanded_Torque, float INV_Torque_Feedback, float INV_Power_On_Timer);
int sendCAN_MC_Torque_And_Timer_Info(float INV_Commanded_Torque, float INV_Torque_Feedback, float INV_Power_On_Timer);

void encode_MC_Read_Write_Param_Response(uint8_t data[8], uint64_t INV_Parameter_Response_Addr, uint64_t INV_Parameter_Response_Write_OK, int64_t INV_Parameter_Response_Data);
int sendCAN_MC_Read_Write_Param_Response(uint64_t INV_Parameter_Response_Addr, uint64_t INV_Parameter_Response_Write_OK, int64_t INV_Parameter_Response_Data);

void encode_MC_Fault_Codes(uint8_t data[8], uint64_t INV_Post_Fault_Lo, uint64_t INV_Post_Fault_Hi, uint64_t INV_Run_Fault_Lo, uint64_t INV_Run_Fault_Hi);
int sendCAN_MC_Fault_Codes(uint64_t INV_Post_Fault_Lo, uint64_t INV_Post_Fault_Hi, uint64_t INV_Run_Fault_Lo, uint64_t INV_Run_Fault_Hi);

void encode_MC_Internal_States(uint8_t data[8], uint64_t INV_VSM_State, uint64_t INV_PWM_Frequency, uint64_t INV_Inverter_State, uint64_t INV_Relay_1_Status, uint64_t INV_Relay_2_Status, uint64_t INV_Relay_3_Status, uint64_t INV_Relay_4_Status, uint64_t INV_Relay_5_Status, uint64_t INV_Relay_6_Status, uint64_t INV_Inverter_Run_Mode, uint64_t INV_Self_Sensing_Assist_Enable, uint64_t INV_Inverter_Discharge_State, uint64_t INV_Inverter_Command_Mode, uint64_t INV_Rolling_Counter, uint64_t INV_Inverter_Enable_State, uint64_t INV_Burst_Model_Mode, uint64_t INV_Key_Switch_Start_Status, uint64_t INV_Inverter_Enable_Lockout, uint64_t INV_Direction_Command, uint64_t INV_BMS_Active, uint64_t INV_BMS_Torque_Limiting, uint64_t INV_Limit_Max_Speed, uint64_t INV_Limit_Hot_Spot, uint64_t INV_Low_Speed_Limiting, uint64_t INV_Limit_Coolant_Derating, uint64_t INV_Limit_Stall_Burst_Model);
int sendCAN_MC_Internal_States(uint64_t INV_VSM_State, uint64_t INV_PWM_Frequency, uint64_t INV_Inverter_State, uint64_t INV_Relay_1_Status, uint64_t INV_Relay_2_Status, uint64_t INV_Relay_3_Status, uint64_t INV_Relay_4_Status, uint64_t INV_Relay_5_Status, uint64_t INV_Relay_6_Status, uint64_t INV_Inverter_Run_Mode, uint64_t INV_Self_Sensing_Assist_Enable, uint64_t INV_Inverter_Discharge_State, uint64_t INV_Inverter_Command_Mode, uint64_t INV_Rolling_Counter, uint64_t INV_Inverter_Enable_State, uint64_t INV_Burst_Model_Mode, uint64_t INV_Key_Switch_Start_Status, uint64_t INV_Inverter_Enable_Lockout, uint64_t INV_Direction_Command, uint64_t INV_BMS_Active, uint64_t INV_BMS_Torque_Limiting, uint64_t INV_Limit_Max_Speed, uint64_t INV_Limit_Hot_Spot, uint64_t INV_Low_Speed_Limiting, uint64_t INV_Limit_Coolant_Derating, uint64_t INV_Limit_Stall_Burst_Model);

void encode_MC_Internal_Voltages(uint8_t data[8], float INV_Ref_Voltage_1_5, float INV_Ref_Voltage_2_5, float INV_Ref_Voltage_5_0, float INV_Ref_Voltage_12_0);
int sendCAN_MC_Internal_Voltages(float INV_Ref_Voltage_1_5, float INV_Ref_Voltage_2_5, float INV_Ref_Voltage_5_0, float INV_Ref_Voltage_12_0);

void encode_MC_Flux_ID_IQ_Info(uint8_t data[8], float INV_Vd_ff, float INV_Vq_ff, float INV_Id, float INV_Iq);
int sendCAN_MC_Flux_ID_IQ_Info(float INV_Vd_ff, float INV_Vq_ff, float INV_Id, float INV_Iq);

void encode_MC_Voltage_Info(uint8_t data[8], float INV_DC_Bus_Voltage, float INV_Output_Voltage, float INV_VAB_Vd_Voltage, float INV_VBC_Vq_Voltage);
int sendCAN_MC_Voltage_Info(float INV_DC_Bus_Voltage, float INV_Output_Voltage, float INV_VAB_Vd_Voltage, float INV_VBC_Vq_Voltage);

void encode_MC_Current_Info(uint8_t data[8], float INV_Phase_A_Current, float INV_Phase_B_Current, float INV_Phase_C_Current, float INV_DC_Bus_Current);
int sendCAN_MC_Current_Info(float INV_Phase_A_Current, float INV_Phase_B_Current, float INV_Phase_C_Current, float INV_DC_Bus_Current);

void encode_MC_Motor_Position_Info(uint8_t data[8], float INV_Motor_Angle_Electrical, int64_t INV_Motor_Speed, float INV_Electrical_Output_Frequency, float INV_Delta_Resolver_Filtered);
int sendCAN_MC_Motor_Position_Info(float INV_Motor_Angle_Electrical, int64_t INV_Motor_Speed, float INV_Electrical_Output_Frequency, float INV_Delta_Resolver_Filtered);

void encode_MC_Digital_Input_Status(uint8_t data[8], uint64_t INV_Digital_Input_1, uint64_t INV_Digital_Input_2, uint64_t INV_Digital_Input_3, uint64_t INV_Digital_Input_4, uint64_t INV_Digital_Input_5, uint64_t INV_Digital_Input_6, uint64_t INV_Digital_Input_7, uint64_t INV_Digital_Input_8);
int sendCAN_MC_Digital_Input_Status(uint64_t INV_Digital_Input_1, uint64_t INV_Digital_Input_2, uint64_t INV_Digital_Input_3, uint64_t INV_Digital_Input_4, uint64_t INV_Digital_Input_5, uint64_t INV_Digital_Input_6, uint64_t INV_Digital_Input_7, uint64_t INV_Digital_Input_8);

void encode_MC_Analog_Input_Voltages(uint8_t data[8], float INV_Analog_Input_1, float INV_Analog_Input_2, float INV_Analog_Input_3, float INV_Analog_Input_4, float INV_Analog_Input_5, float INV_Analog_Input_6);
int sendCAN_MC_Analog_Input_Voltages(float INV_Analog_Input_1, float INV_Analog_Input_2, float INV_Analog_Input_3, float INV_Analog_Input_4, float INV_Analog_Input_5, float INV_Analog_Input_6);

void encode_MC_Temperature_Set_3(uint8_t data[8], float INV_Coolant_Temp, float INV_Hot_Spot_Temp, float INV_Motor_Temp, float INV_Torque_Shudder);
int sendCAN_MC_Temperature_Set_3(float INV_Coolant_Temp, float INV_Hot_Spot_Temp, float INV_Motor_Temp, float INV_Torque_Shudder);

void encode_MC_Temperature_Set_2(uint8_t data[8], float INV_Control_Board_Temp, float INV_RTD1_Temperature, float INV_RTD2_Temperature, float INV_Stall_Burst_Model_Temp);
int sendCAN_MC_Temperature_Set_2(float INV_Control_Board_Temp, float INV_RTD1_Temperature, float INV_RTD2_Temperature, float INV_Stall_Burst_Model_Temp);

void encode_MC_Temperature_Set_1(uint8_t data[8], float INV_Module_A_Temp, float INV_Module_B_Temp, float INV_Module_C_Temp, float INV_Gate_Driver_Board_Temp);
int sendCAN_MC_Temperature_Set_1(float INV_Module_A_Temp, float INV_Module_B_Temp, float INV_Module_C_Temp, float INV_Gate_Driver_Board_Temp);

void encode_MC_Firmware_Info(uint8_t data[8], uint64_t INV_Project_Code_EEP_Ver, uint64_t INV_SW_Version, uint64_t INV_DateCode_MMDD, uint64_t INV_DateCode_YYYY);
int sendCAN_MC_Firmware_Info(uint64_t INV_Project_Code_EEP_Ver, uint64_t INV_SW_Version, uint64_t INV_DateCode_MMDD, uint64_t INV_DateCode_YYYY);

void encode_MC_Fast_Info(uint8_t data[8], float INV_Fast_Torque_Command, float INV_Fast_Torque_Feedback, int64_t INV_Fast_Motor_Speed, float INV_Fast_DC_Bus_Voltage);
int sendCAN_MC_Fast_Info(float INV_Fast_Torque_Command, float INV_Fast_Torque_Feedback, int64_t INV_Fast_Motor_Speed, float INV_Fast_DC_Bus_Voltage);

#ifdef __cplusplus
}
#endif

#endif /* CAN_SIGNALS_H */
